[package]
name = "papyrus"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
datafusion = "45.0.0"
parquet = "54.2.1"
serde = "1.0.218"
tokio = { version = "1.43.0" , features = ["rt-multi-thread"] }

